name: Build Android APK

on:
  workflow_dispatch:     # Permet de lancer le build à la main
  push:
    branches: [ main ]   # Build aussi à chaque push sur main (optionnel)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      # Build en debug pour éviter la gestion du keystore de release
      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: koel-player-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
